### ISSUE TITLE
Limit of resources for worker is not flexiable.

### ISSUE THREAD

**Issue by bbbmj** [caicloud/cyclone#527]
**Description**:

Every worker needs different resources configuration, we need a more flexible way to adjust it.

**What's more**:

We need more limits such as `Container Cap` & `Max connections to Kubernetes API` to ensure cyclone not to cost too many resources. 

**Advice**

Now, Jenkins-kubernetes plugin support `Using yaml to Define Pod Templates` with the hope to support any possible value in Kubernetes Pod object, it's awesome for the user like me. 
https://github.com/jenkinsci/kubernetes-plugin#using-yaml-to-define-pod-templates
Maybe, we can refer to this?

/kind feature
/cc @supereagle @zhujian7

**Comment by zhujian7** [comment]
yeah, it is necessary to make the limiting resources for worker more flexiable, and we are doing some work about it, here are some PRs:
- [support running worker in user cluster](https://github.com/caicloud/cyclone/pull/507)
- [support configuring resource quota for worker](https://github.com/caicloud/cyclone/pull/526)

i think we could adjust cpu and memory flexiblly due to above. but `Max connections to Kubernetes API` and others are not supported now.
